# Setup
title:               Mohammed Vasim
tagline:             'Profile'
description:         'Aspiring AI Research Scientist & Future Entrepreneur | AI Engineering | Computer Vision Engineer at ZestIoT | GenAI Developer | Driving Innovation through AI & Data.'
url:                 http://mohdvasm.github.io/profile/
baseurl:             '/profile'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mohammed Vasim
  url:               https://www.linkedin.com/in/mohdvasm/
  email:             mohd.vasim@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
